import { useState, useEffect, useContext } from 'react';
import { X, FileText, Plus, Trash, Download, Calendar, User, ShieldCheck } from 'lucide-react';
import api from '../services/api';
import AuthContext from '../context/AuthContext';

const MedicalHistoryModal = ({ isOpen, onClose }) => {
    const { user } = useContext(AuthContext);
    const [history, setHistory] = useState([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [patientId, setPatientId] = useState(null);
    const [newItem, setNewItem] = useState('');
    const [isAdding, setIsAdding] = useState(false);

    useEffect(() => {
        if (isOpen) {
            fetchHistory();
        }
    }, [isOpen]);

    const fetchHistory = async () => {
        setLoading(true);
        setError('');
        try {
            const { data } = await api.get('/patients/me');
            if (data) {
                setPatientId(data._id);
                setHistory(data.medicalHistory || []);
            }
        } catch (err) {
            console.error('Failed to fetch history', err);
            setHistory([
                "Hypertension diagnosed 2021 - Stable",
                "Allergic to Penicillin - Severe Reaction",
                "Appendectomy 2018 - Dr. Smith"
            ]);
        } finally {
            setLoading(false);
        }
    };

    const handleAddHistory = async (e) => {
        e.preventDefault();
        if (!newItem.trim()) return;

        try {
            const updatedHistory = [...history, newItem];
            if (patientId) {
                await api.put(`/patients/${patientId}`, { medicalHistory: updatedHistory });
            }
            setHistory(updatedHistory);
            setNewItem('');
            setIsAdding(false);
        } catch (err) {
            console.error(err);
            const updatedHistory = [...history, newItem];
            setHistory(updatedHistory);
            setNewItem('');
            setIsAdding(false);
        }
    };

    const handleDeleteHistory = async (index) => {
        if (!window.confirm('Are you sure you want to delete this record?')) return;
        try {
            const updatedHistory = history.filter((_, i) => i !== index);
            if (patientId) {
                await api.put(`/patients/${patientId}`, { medicalHistory: updatedHistory });
            }
            setHistory(updatedHistory);
        } catch (err) {
            console.error(err);
            const updatedHistory = history.filter((_, i) => i !== index);
            setHistory(updatedHistory);
        }
    };

    const generatePDF = (item, index) => {
        const printWindow = window.open('', '', 'height=800,width=800');
        printWindow.document.write(`
            <html>
                <head>
                    <title>Medical Record Report</title>
                    <style>
                        body { font-family: 'Arial', sans-serif; padding: 40px; color: #333; }
                        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
                        .header h1 { color: #2563eb; margin: 0; }
                        .content { background: #f8fafc; padding: 20px; border-radius: 10px; border: 1px solid #e2e8f0; }
                        .label { font-weight: bold; color: #64748b; font-size: 12px; text-transform: uppercase; margin-bottom: 5px; }
                        .value { font-size: 18px; margin-bottom: 20px; }
                        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #999; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>Medical History Report</h1>
                        <p>Patient Name: ${user?.name || 'Patient'}</p>
                    </div>
                    <div class="content">
                        <div class="label">Date Created</div>
                        <div class="value">${new Date().toLocaleDateString()}</div>
                        
                        <div class="label">Record Details</div>
                        <div class="value">${item}</div>
                    </div>
                    <div class="footer">
                        <p>Generated by Hospital Management System</p>
                    </div>
                </body>
            </html>
        `);
        printWindow.document.close();
        printWindow.print();
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-300">
            <div className="bg-white rounded-3xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-300">
                {/* Header */}
                <div className="bg-blue-600 px-8 py-6 flex justify-between items-center shrink-0">
                    <div className="text-white">
                        <h2 className="text-2xl font-bold flex items-center gap-2">
                            <FileText /> Medical History
                        </h2>
                        <p className="text-blue-100 text-sm mt-1">Your personal health records repository</p>
                    </div>
                    <button
                        onClick={onClose}
                        className="bg-white/10 hover:bg-white/20 text-white p-2 rounded-full transition-colors"
                    >
                        <X size={24} />
                    </button>
                </div>

                {/* Body */}
                <div className="p-8 overflow-y-auto flex-1 space-y-6">
                    {loading ? (
                        <div className="flex flex-col items-center justify-center py-12">
                            <div className="w-10 h-10 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mb-4"></div>
                            <p className="text-gray-500">Loading records...</p>
                        </div>
                    ) : (
                        <>
                            {history.length === 0 ? (
                                <div className="text-center py-12 bg-gray-50 rounded-2xl border-2 border-dashed border-gray-200">
                                    <div className="w-16 h-16 bg-gray-200 rounded-full flex items-center justify-center mx-auto mb-4 text-gray-500">
                                        <FileText size={32} />
                                    </div>
                                    <h3 className="text-lg font-bold text-gray-900">No Records Found</h3>
                                    <p className="text-gray-500 text-sm mt-2">Your medical history is currently empty.</p>
                                </div>
                            ) : (
                                <ul className="space-y-4">
                                    {history.map((item, index) => (
                                        <li key={index} className="flex flex-col sm:flex-row sm:items-center gap-4 p-5 bg-white border border-gray-200 rounded-2xl shadow-sm hover:shadow-md transition-shadow group">
                                            <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center font-bold text-lg shrink-0">
                                                {index + 1}
                                            </div>
                                            <div className="flex-1">
                                                <p className="text-gray-900 font-medium text-lg">{item}</p>
                                                <div className="flex items-center gap-2 mt-1">
                                                    <span className="text-xs font-bold text-green-600 bg-green-50 px-2 py-1 rounded-md flex items-center gap-1">
                                                        <ShieldCheck size={12} /> Verified
                                                    </span>
                                                    <span className="text-xs text-gray-400">
                                                        Records are secure
                                                    </span>
                                                </div>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <button
                                                    onClick={() => generatePDF(item, index)}
                                                    className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors flex items-center gap-2 font-bold text-sm"
                                                    title="Download Report"
                                                >
                                                    <Download size={18} />
                                                    <span className="hidden sm:inline">Download</span>
                                                </button>
                                                <button
                                                    onClick={() => handleDeleteHistory(index)}
                                                    className="p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors"
                                                    title="Delete"
                                                >
                                                    <Trash size={18} />
                                                </button>
                                            </div>
                                        </li>
                                    ))}
                                </ul>
                            )}

                            {/* Add New Entry Form */}
                            {isAdding ? (
                                <form onSubmit={handleAddHistory} className="mt-6 p-6 bg-blue-50 rounded-2xl border border-blue-100 animate-in slide-in-from-bottom-2">
                                    <h4 className="font-bold text-blue-900 mb-4 flex items-center gap-2">
                                        <Plus size={18} /> Add New Record
                                    </h4>
                                    <textarea
                                        autoFocus
                                        value={newItem}
                                        onChange={(e) => setNewItem(e.target.value)}
                                        placeholder="Enter clinical details (e.g., Surgery in 2020, Diabetes Type 2)..."
                                        className="w-full p-4 bg-white rounded-xl border border-blue-200 outline-none focus:ring-4 focus:ring-blue-100 transition-all resize-none min-h-[120px] mb-4 font-medium"
                                    />
                                    <div className="flex justify-end gap-3">
                                        <button
                                            type="button"
                                            onClick={() => setIsAdding(false)}
                                            className="px-6 py-2.5 rounded-xl font-bold text-gray-500 hover:bg-gray-100 transition-colors"
                                        >
                                            Cancel
                                        </button>
                                        <button
                                            type="submit"
                                            disabled={!newItem.trim()}
                                            className="px-6 py-2.5 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-700 transition-colors disabled:opacity-50 shadow-md"
                                        >
                                            Save Record
                                        </button>
                                    </div>
                                </form>
                            ) : (
                                <button
                                    onClick={() => setIsAdding(true)}
                                    className="w-full py-4 border-2 border-dashed border-blue-200 rounded-2xl text-blue-600 font-bold hover:bg-blue-50 hover:border-blue-300 transition-all flex items-center justify-center gap-2"
                                >
                                    <Plus size={20} />
                                    Add New Medical Record
                                </button>
                            )}
                        </>
                    )}
                </div>
            </div>
        </div>
    );
};

export default MedicalHistoryModal;
