import { useState, useEffect, useContext } from 'react';
import { FileText, Download, Calendar, User, Activity, AlertCircle } from 'lucide-react';
import api from '../services/api';
import AuthContext from '../context/AuthContext';

const MedicalRecords = () => {
    const { user } = useContext(AuthContext);
    const [records, setRecords] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        fetchRecords();
    }, []);

    const fetchRecords = async () => {
        try {
            const { data } = await api.get('/medical-records');
            setRecords(data);
        } catch (err) {
            console.error('Failed to fetch medical records:', err);
            setError('Could not load medical records.');
        } finally {
            setLoading(false);
        }
    };

    const generatePDF = (record) => {
        // Simple printable view for now
        const printWindow = window.open('', '', 'height=600,width=800');
        printWindow.document.write('<html><head><title>Medical Record</title>');
        printWindow.document.write('<style>body{font-family:sans-serif; padding: 2rem;} .header{border-bottom: 2px solid #333; padding-bottom: 1rem; margin-bottom: 2rem;} h1{color: #2563eb;} .meta{display:grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 2rem;} .label{font-weight:bold; color: #666;} .content{margin-bottom: 2rem;} .section{background: #f8fafc; padding: 1rem; border-radius: 8px; margin-bottom: 1rem;} .footer{margin-top: 4rem; text-align: center; font-size: 0.8rem; color: #999;}</style>');
        printWindow.document.write('</head><body>');
        printWindow.document.write('<div class="header"><h1>MediCare Medical Report</h1><p>Official Digital Record</p></div>');
        printWindow.document.write(`<div class="meta"><div><span class="label">Patient:</span> <p>${record.patient?.user?.name || 'N/A'}</p></div><div><span class="label">Doctor:</span> <p>Dr. ${record.doctor?.user?.name || 'N/A'}</p></div><div><span class="label">Date:</span> <p>${new Date(record.date).toLocaleDateString()}</p></div><div><span class="label">Record ID:</span> <p>${record._id}</p></div></div>`);
        printWindow.document.write(`<div class="content"><div class="section"><h3>Diagnosis</h3><p>${record.diagnosis}</p></div>`);
        printWindow.document.write(`<div class="section"><h3>Prescription / Treatment</h3><p>${record.prescription}</p></div></div>`);
        printWindow.document.write('<div class="footer"><p>Generated by MediCare System. This is a computer generated document.</p></div>');
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    };

    return (
        <div className="space-y-8 animate-in fade-in duration-500">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-black text-slate-900 tracking-tight">Medical Records</h1>
                    <p className="text-slate-500 font-medium mt-1">View and download your official medical history and prescriptions</p>
                </div>
            </div>

            {loading ? (
                <div className="flex items-center justify-center py-20">
                    <div className="w-12 h-12 border-4 border-primary-500 border-t-transparent rounded-full animate-spin"></div>
                </div>
            ) : error ? (
                <div className="p-6 bg-rose-50 text-rose-500 rounded-2xl flex items-center gap-4 border border-rose-100">
                    <AlertCircle size={24} />
                    <span className="font-bold">{error}</span>
                </div>
            ) : records.length === 0 ? (
                <div className="text-center py-20 bg-white rounded-[2rem] border border-slate-100 shadow-sm">
                    <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-6 text-slate-300">
                        <FileText size={40} />
                    </div>
                    <h3 className="text-lg font-black text-slate-800">No Records Found</h3>
                    <p className="text-slate-400 font-medium max-w-xs mx-auto mt-2">You don't have any formal medical records generated by doctors yet.</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {records.map((record) => (
                        <div key={record._id} className="bg-white p-8 rounded-[2rem] border border-slate-100 shadow-sm hover:shadow-xl transition-all duration-300 group">
                            <div className="flex justify-between items-start mb-6">
                                <div className="flex items-center gap-4">
                                    <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center">
                                        <FileText size={24} />
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-slate-900">Diagnosis Report</h3>
                                        <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">{new Date(record.date).toLocaleDateString()}</p>
                                    </div>
                                </div>
                                <button
                                    onClick={() => generatePDF(record)}
                                    className="p-3 bg-slate-50 text-slate-400 hover:bg-primary-50 hover:text-primary-600 rounded-xl transition-colors"
                                    title="Download PDF"
                                >
                                    <Download size={20} />
                                </button>
                            </div>

                            <div className="space-y-4 mb-6">
                                <div className="p-4 bg-slate-50 rounded-2xl">
                                    <p className="text-xs font-black text-slate-400 uppercase tracking-widest mb-1">Diagnosis</p>
                                    <p className="font-semibold text-slate-700">{record.diagnosis}</p>
                                </div>
                                <div>
                                    <p className="text-xs font-black text-slate-400 uppercase tracking-widest mb-1">Prescription</p>
                                    <p className="font-medium text-slate-600 leading-relaxed">{record.prescription}</p>
                                </div>
                            </div>

                            <div className="flex items-center gap-3 pt-6 border-t border-slate-50">
                                <div className="w-8 h-8 bg-slate-100 rounded-full flex items-center justify-center text-slate-500">
                                    <User size={14} />
                                </div>
                                <span className="text-sm font-bold text-slate-600">Dr. {record.doctor?.user?.name}</span>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

export default MedicalRecords;
